apiVersion: v1
kind: Service
metadata:
    name: "aksdemoyossi-7c54"
    labels:
        app: "aksdemoyossi-7c54"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksdemoyossi-7c54"