on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksyossicoreg.azurecr.io
        username: ${{ secrets.acr_aksyossicoreg_username }}
        password: ${{ secrets.acr_aksyossicoreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t aksyossicoreg.azurecr.io/aksdemoyossi:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push aksyossicoreg.azurecr.io/aksdemoyossi:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemoyossi_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-demo-yossib666 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-demo-yossib666`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-demo-yossib666
        container-registry-url: aksyossicoreg.azurecr.io
        container-registry-username: ${{ secrets.acr_aksyossicoreg_username }}
        container-registry-password: ${{ secrets.acr_aksyossicoreg_password }}
        secret-name: aksdemoyossidockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-demo-yossib666
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          aksyossicoreg.azurecr.io/aksdemoyossi:${{ github.sha }}
        imagepullsecrets: |
          aksdemoyossidockerauth
